# A Neural Network with Perceptron

In [8]:
import pandas as pd
import numpy as np
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

from sklearn.linear_model import Perceptron

In [9]:
iris_data = datasets.load_iris()
X = iris_data.data
y = iris_data.target

X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

Let's split the data

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

Let's normalize the data

In [11]:
standardize = StandardScaler()

standardized_x_train = standardize.fit_transform(X_train)
standardized_x_test  = standardize.fit_transform(X_test)

standardized_x_test[0:10,]

array([[ 0.80634543, -0.4205122 ,  1.12613263,  1.45914551],
       [-1.66205894, -0.17315208, -1.35450918, -1.29395922],
       [-1.04495785, -1.40995268, -0.23231407, -0.19271733],
       [-0.30443654,  3.04252946, -1.35450918, -1.29395922],
       [ 0.80634543, -0.4205122 ,  1.12613263,  1.32149027],
       [ 0.06582412, -0.4205122 ,  0.83081813,  1.73445598],
       [-1.29179828,  0.56892827, -1.23638338, -1.29395922],
       [-0.0575961 ,  0.07420804,  0.29925203,  0.08259314],
       [ 0.06582412, -0.66787232,  0.83081813,  1.0461798 ],
       [-0.92153763,  0.07420804, -1.23638338, -1.29395922]])

Initiate the Perceptron

eta0 = Constant by which the updates are multiplied.

tol= toleration

In [12]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)
perceptron.fit(standardized_x_train, y_train.ravel())

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.15,
      fit_intercept=True, max_iter=50, n_iter=None, n_iter_no_change=5,
      n_jobs=None, penalty=None, random_state=15, shuffle=True, tol=0.001,
      validation_fraction=0.1, verbose=0, warm_start=False)

In [13]:
y_pred = perceptron.predict(standardized_x_test)

In [14]:
print(y_test)

[2 0 1 0 2 2 0 1 2 0 1 1 2 0 0 0 0 0 1 1 1 1 2 1 1 2 2 2 0 1]


In [15]:
print(y_pred)

[2 0 1 0 2 2 0 1 2 0 1 2 1 0 0 0 0 0 1 1 1 1 2 1 2 2 2 2 0 2]


In [16]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.89      0.73      0.80        11
           2       0.73      0.89      0.80         9

   micro avg       0.87      0.87      0.87        30
   macro avg       0.87      0.87      0.87        30
weighted avg       0.88      0.87      0.87        30

